-- 상담왕 등극기: 로그인 접속 기록 테이블
-- 기존 quiz_results / questions / settings 데이터는 변경하지 않습니다.

create table if not exists public.access_logs (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  access_date date not null default (timezone('Asia/Seoul', now()))::date,
  created_at timestamptz not null default now()
);

create index if not exists access_logs_phone_idx on public.access_logs (phone);
create index if not exists access_logs_access_date_idx on public.access_logs (access_date desc);
create index if not exists access_logs_created_at_idx on public.access_logs (created_at desc);

alter table public.access_logs enable row level security;

drop policy if exists "anon_insert_access_logs" on public.access_logs;
create policy "anon_insert_access_logs"
on public.access_logs for insert to anon
with check (
  char_length(name) between 1 and 100
  and phone ~ '^[0-9]{10,11}$'
);

-- 현재 admin.html은 기존 프로젝트와 동일하게 anon 키를 사용합니다.
-- Supabase Auth 도입 전까지 관리자 조회 화면을 작동시키기 위한 읽기 정책입니다.
drop policy if exists "anon_read_access_logs" on public.access_logs;
create policy "anon_read_access_logs"
on public.access_logs for select to anon
using (true);
